project:
  type: website
  output-dir: _site
  pre-render:
    - ../shared/bash/clean.sh
    - ../shared/python/precompute_reading_stats.py
    - ../shared/python/render_timer.py start
  post-render:
    - ../shared/bash/sync-en.sh
    - ../shared/python/render_timer.py end
  preview:
    port: 7777

profiles:
  - dev
  - prod

lang: en
reading-time:
  seconds-per-syllable: 0.2

hashtag:
  auto-scan: true
  default-provider: "x"

metadata:
  external-refs-title: "External References"
  phones:
    "0533XXX9779": "The phone number used by Nevzat Bahtiyar"
    "0536XXX7120": "The phone number used by Yüksel Güran"
    "0539XXX7358": "The phone number used by Enes Güran"
    "0530XXX0653": "The phone number used by Salim Güran"
    "0531XXX1521": "The phone number used by Selim Atasoy"
  plates:
    "23 XX 630": "The red vehicle used by Nevzat Bahtiyar"
    "47 XX 388": "The vehicle used by Salim Güran"
    "56 XX 763": "The vehicle used by Osman Güran"
  abbr:
    AMFT: "Attorneys’ Minimum Fee Tariff - Avukatlık Asgari Ücret Tarifesi"
    FIR: "Forensic Interview Room - (Adli Görüşme Odası)"
    BTK: "Information and Communication Technologies Authority - (Bilgi Teknolojileri ve İletişim Kurumu)"
    CPC: "Criminal Procedure Code - (Ceza Muhakemesi Kanunu)"
    CFM: "Council of Forensic Medicine - (Adli Tıp Kurumu)"
    DEPSAŞ: "Dicle Elektrik Perakende Satış A.Ş. - (Dicle Electricity Retail Sales Inc.)"
    GPS: "Global Positioning System"
    HCC: "High Criminal Court - (Ağır Ceza Mahkemesi)"
    HTS: "Historical Traffic Search"
    JASAT: "Gendarmerie Crime Investigation Team - (Jandarma Suç Araştırma Timi)"
    mtDNA: "Mitochondrial DNA"
    TPC: "Turkish Penal Code - (Türk Ceza Kanunu)"
    TÜBİTAK: "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu - (The Scientific and Technological Research Council of Turkey)"
    SEGBİS: "Ses ve Görüntü Bilişim Sistemi - (Audio and Visual Information System)"
    UKB: "Ulusal Kriminal Büro - (National Criminal Bureau)"

  participant:
    victim:
      - variant: true
      - text: Victim
      - prefix:
        - Victim
      - suffix:
      - names:
        - "Narin Güran"
    suspect:
      - variant: true
      - text: Defendant
      - prefix:
        - Defendant
      - names:
        - "Nevzat Bahtiyar"
        - "Yüksel Güran"
        - "Salim Güran"
        - "Enes Güran"
    complainant:
      - variant: true
      - text: Complainant
      - prefix:
        - Complainant
      - names:
        - "Arif Güran"
    witness:
      - variant: true
      - text: Witness
      - names:
        - "Muhammed Emre Güran"
        - "Maşşallah Güran"
        - "Maşallah Güran"
        - "Gazal Bahtiyar"
        - "Muhammed Kaya"
        - "Baran Güran"
        - "Osman Güran"
    judge:
      - text: Judge
      - names:
        - "Presiding Judge"
        - "Associate Judge"
    prosecutor:
      - text: Prosecutor
      - names:
        - "Trial Prosecutor"
    kdb:
      - text: "Diyarbakır Bar Association"
      - prefix:
        - "Law."
      - names:
        - "Nahit Eren"
        - "Aydın Özdemir"
        - "Erdem Kaya"
        - "Mehdi Özdemir"
        - "Asya Cemre Işık"
        - "Berat Kocakaya"
        - "Derya Yıldırım"
        - "Metin Arkaş"
    ashb:
      - text: "Ministry of Family and Social Services"
      - prefix:
        - "Law."
      - names:
        - "Şeyhmus Erdoğan"
        - "Abdullah Yılmaz"
        - "Elif Aslı Şahin Torun"
        - "Emine Akçalı"
    mudafi-enes:
      - text: "Defense Counsel for Enes Güran"
      - prefix:
        - "Law."
      - names:
        - "Mahir Akbilek"
        - "Mustafa Demir"
        - "Muhammed Fatih Demir"
        - "M. Fatih Demir"
        - "Recep Kızılok"
    mudafi-yuksel:
      - text: "Defense Counsel for Yüksel Güran"
      - prefix:
        - "Law."
      - names:
        - "Yılmaz Demiroğlu"
        - "Tuncay Erkuş"
        - "Furkan Çakır"
        - "Doğuş Can Kurucu"
        - "Sanık Yüksel Müdafi"
    mudafi-salim:
      - text: "Defense Counsel for Salim Güran"
      - prefix:
        - "Law."
      - names:
        - "Onur Akdağ"
    mudafi-nevzat:
      - text: "Defense Counsel for Nevzat Bahtiyar"
      - prefix:
        - "Law."
      - names:
        - "Ali Eryılmaz"
        - "Adnan Ataş"
    others:
      - text: "Other Participants"
      - names:
        - "Interpreter"
        - "Female Lawyer"

highlight-style: a11y

website:
  title: "Narin"
  site-url: https://narinveailesiicinadalet.github.io/en/
  repo-url: https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io
  image: resources/images/narin_en.png
  favicon: resources/icons/favicon.png
  open-graph: true
  twitter-card: true
  repo-actions: [edit, issue]
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    left:
      - text: "{{< meta modification-date >}}"
      - text: "{{< meta render-time-footer >}}"
    center:
      - text: "<a class='nav-link footer-icon' href='/about' aria-label='About'><span class='svg-mask'></span>About</a>"
      - text:  "<a class='nav-link bi bi-patch-question' href='/faq' aria-label='SSS'><span class='svg-mask'></span> FAQ</a>"
    right:
      - icon: twitter-x
        href: https://X.com/narinveailesi
        aria-label: Twitter
      - icon: github
        href: https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io
        aria-label: GitHub
      - icon: rss
        href: https://quarto.org/blog/index.xml
        aria-label: Blog RSS
  navbar:
    background: light
    logo: resources/icons/narin.png
    logo-href: /
    title: false
    collapse-below: lg
    left:
      - text: "Trial"
        menu:
          - text: "Summary"
            icon: "file-medical"
            href: trial/index.qmd
          - text: "Testimonies"
            icon: "chat-left-text"
            href: trial/testimonies/index.qmd
          - text: "Defenses"
            icon: "files"
            href: trial/defenses/index.qmd
          - text: "Judgment"
            icon: "list-check"
            href: trial/judgment.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "Map"
        href: map/index.qmd
      - text: "Gallery"
        menu:
          - text: "Images"
            icon: "images"
            href: gallery/images/index.qmd
          - text: "Videos"
            icon: "camera-video"
            href: gallery/videos/index.qmd
      - text: "Help"
        menu:
          - text: "Guide"
            icon: "signpost-split"
            href: guide/index.qmd
          - text: "Report an issue"
            icon: "bug"
            href: "https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io/issues"
          - text: "Discussion"
            icon: "chat-right-text"
            href: "https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io/discussions"
          - text: "FAQ"
            icon: "question-circle"
            href: faq/index.qmd
    tools:
      - icon: twitter-x
        href: https://X.com/narinveailesi
        text: Twitter
      - icon: github
        href: https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io
        text: GitHub
      - icon: chat-quote
        href: https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io/discussions
        text: Tartışma

  sidebar:
    - id: testimonies
      title: "Testimonies"
      style: "docked"
      collapse-level: 4
      align: left
      contents:
      - section: Testimonies
        href: trial/testimonies/index.qmd
        contents:
          - section: Suspects
            icon: "chat-left-text"
            href: trial/testimonies/suspect/index.qmd
            contents:
              - section: "Nevzat BAHTİYAR"
                icon: person-fill
                href: trial/testimonies/suspect/bahtiyar_nevzat/index.qmd
                contents:
                - text: "Trial"
                  icon: dot
                  href: trial/testimonies/suspect/bahtiyar_nevzat/testimony.qmd
              - section: "Yüksel GÜRAN"
                icon: person-fill
                href: trial/testimonies/suspect/guran_yuksel/index.qmd
                contents:
                - text: "Trial"
                  icon: dot
                  href: trial/testimonies/suspect/guran_yuksel/testimony.qmd
              - section: "Enes GÜRAN"
                icon: person-fill
                href: trial/testimonies/suspect/guran_enes/index.qmd
                contents:
                - text: "Trial"
                  icon: dot
                  href: trial/testimonies/suspect/guran_enes/testimony.qmd
              - section: "Salim GÜRAN"
                icon: person-fill
                href: trial/testimonies/suspect/guran_salim/index.qmd
                contents:
                - text: "Trial"
                  icon: dot
                  href: trial/testimonies/suspect/guran_salim/testimony.qmd
          - section: Witnesses
            icon: "chat-left-text"
            href: trial/testimonies/witness/index.qmd
            contents:
              - text: "Gazal BAHTİYAR"
                icon: person
                href: trial/testimonies/witness/bahtiyar_gazal.qmd
              - text: "Baran GÜRAN"
                icon: person
                href: trial/testimonies/witness/guran_baran.qmd
              - text: "Maşşallah GÜRAN"
                icon: person
                href: trial/testimonies/witness/guran_masallah.qmd
              - text: "Osman GÜRAN"
                icon: person
                href: trial/testimonies/witness/guran_osman.qmd
              - text: "Muhammed KAYA"
                icon: person
                href: trial/testimonies/witness/kaya_muhammed.qmd

    - id: defenses
      title: "Defenses"
      style: "docked"
      collapse-level: 3
      align: left
      contents:
        - section: Defenses
          icon: "files"
          href: trial/defenses/index.qmd
          contents:
            - section: "Nevzat BAHTİYAR"
              icon: file-earmark-person
              href: trial/defenses/bahtiyar_nevzat/index.qmd
              contents:
              - text: "Law. Ali ERYILMAZ"
                icon: dot
                href: trial/defenses/bahtiyar_nevzat/eryilmaz_ali.qmd
              - text: "Law. Adnan ATAŞ"
                icon: dot
                href: trial/defenses/bahtiyar_nevzat/atas_adnan.qmd
            - section: "Yüksel GÜRAN"
              icon: file-earmark-person
              href: trial/defenses/guran_yuksel/index.qmd
              contents:
              - text: "Law. Yılmaz DEMİROĞLU"
                icon: dot
                href: trial/defenses/guran_yuksel/demiroglu_yilmaz.qmd
              - text: "Law. Furkan ÇAKIR"
                icon: dot
                href: trial/defenses/guran_yuksel/cakir_furkan.qmd
              - text: "Law. Doğuş Can KURUCU"
                icon: dot
                href: trial/defenses/guran_yuksel/kurucu_doguscan.qmd
            - section: "Enes GÜRAN"
              icon: file-earmark-person
              href: trial/defenses/guran_enes/index.qmd
              contents:
              - text: "Law. Mahir AKBİLEK"
                icon: dot
                href: trial/defenses/guran_enes/akbilek_mahir.qmd
              - text: "Law. M. Fatih DEMİR"
                icon: dot
                href: trial/defenses/guran_enes/demir_fatih.qmd
              - text: "Law. Recep KIZILOK"
                icon: dot
                href: trial/defenses/guran_enes/kizilok_recep.qmd
              - text: "Law. Mustafa DEMİR"
                icon: dot
                href: trial/defenses/guran_enes/demir_mustafa.qmd
            - section: "Salim GÜRAN"
              icon: file-earmark-person
              href: trial/defenses/guran_salim/index.qmd
              contents:
              - text: "Law. Onur AKDAĞ"
                icon: dot
                href: trial/defenses/guran_salim/akdag_onur.qmd

    - id: blog
      title: "Blog"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
      - section: Authors
        contents:
          - text: Alaattin Oğuz
            icon: "file-earmark-person"
            href: blog/posts/alaattin-oguz/index.qmd
          - text: Ali Duran Topuz
            icon: "file-earmark-person"
            href: blog/posts/ali-duran-topuz/index.qmd
          - text: Cansu Çamlıbel
            icon: "file-earmark-person"
            href: blog/posts/cansu-camlibel/index.qmd
          - text: Cemal Tunçdemir
            icon: "file-earmark-person"
            href: blog/posts/cemal-tuncdemir/index.qmd
          - text: E. Miham Akkul
            icon: "file-earmark-person"
            href: blog/posts/miham-akkul/index.qmd
          - text: Faruk Bildirici
            icon: "file-earmark-person"
            href: blog/posts/faruk-bildirici/index.qmd
          - text: Hilal Seven
            icon: "file-earmark-person"
            href: blog/posts/hilal-seven/index.qmd
          - text: Melek Borak
            icon: "file-earmark-person"
            href: blog/posts/melek-borak/index.qmd
          - text: Nazife Güngör
            icon: "file-earmark-person"
            href: blog/posts/nazife-gungor/index.qmd
          - text: Ömer Faruk Gergerlioğlu
            icon: "file-earmark-person"
            href: blog/posts/omer-faruk-gergerlioglu/index.qmd
          - text: Rana Polat Sönmez
            icon: "file-earmark-person"
            href: blog/posts/rana-polat-sonmez/index.qmd
          - text: Sadık Güleç
            icon: "file-earmark-person"
            href: blog/posts/sadik-gulec/index.qmd
          - text: Sevilay Çelenk
            icon: "file-earmark-person"
            href: blog/posts/sevilay-celenk/index.qmd
          - text: Tuncay Beşikçi
            icon: "file-earmark-person"
            href: blog/posts/tuncay-besikci/index.qmd
          - text: Yıldıray Oğur
            icon: "file-earmark-person"
            href: blog/posts/yildiray-ogur/index.qmd
      - section: News Sites
        contents:
          - text: bianet
            icon: "newspaper"
            href: blog/posts/bianet/index.qmd
          - text: Serbestiyet
            icon: "newspaper"
            href: blog/posts/serbestiyet/index.qmd
          - text: T24
            icon: "newspaper"
            href: blog/posts/t24/index.qmd

    - id: images
      title: "Images"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
      - section: Images
        icon: "images"
        href: gallery/images/index.qmd
        contents:
          - text: Crime Scene
            icon: "geo-alt"
            href: gallery/images/olay-yeri.qmd
          - text: Hearings
            icon: "building"
            href: gallery/images/durusmalar.qmd
          - text: Justice Vigil
            icon: "megaphone"
            href: gallery/images/adalet-nobeti.qmd
          - text: Arif Güran's Family
            icon: "people"
            href: gallery/images/aile.qmd
          - text: Press & Interviews
            icon: "mic"
            href: gallery/images/basin-roportaj.qmd
          - text: Narin
            icon: "person-heart"
            href: gallery/images/narin.qmd

    - id: videos
      title: "Videos"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
      - section: Videos
        icon: "camera-video"
        href: gallery/videos/index.qmd
        contents:
          - text: Documentaries
            icon: "film"
            href: gallery/videos/belgeseller/index.qmd
          - text: Past Broadcasts
            icon: "broadcast"
            href: gallery/videos/gecmis-yayinlar/index.qmd
          - text: Rojda Altıntaş
            icon: "camera-reels"
            href: gallery/videos/rojda-altintas/index.qmd
          - text: Uğur Korkmaz
            icon: "camera-reels"
            href: gallery/videos/ugur-korkmaz/index.qmd

format:
  html:
    link-external-newwindow: true   # external linklere target="_blank"
    link-external-icon: true
    respect-user-color-scheme: true
    anchor-sections: false
    toc: true
    theme:
      light: [cosmo, resources/scss/theme.scss]
      dark: [cosmo, resources/scss/theme-dark.scss]
    css:
      - resources/css/styles.css
      - resources/css/span.css
      - resources/css/boxes.css
      - resources/css/mobile-toc.css
      - resources/css/highlight-speakers.css
      - resources/css/image-zoom.css
      - resources/css/refs.css
      - resources/css/stats_panel.css
      - resources/css/overlay.css
      - resources/css/margin-listing.css
      - resources/css/photo-gallery.css

    include-after-body:
      - text: |
          <script src="/resources/js/overlay.js"></script>
          <script src="/resources/js/hide-footer-actions.js"></script>
          <script src="/resources/js/external-links.js"></script>
          <script src="/resources/js/lang-switch-inject.js"></script>
          <script src="/resources/js/lang-switch-handler.js"></script>
          <script src="/resources/js/plate-tooltip.js"></script>
          <script src="/resources/js/toc-smooth-scroll.js"></script>
          <script src="/resources/js/mobile-toc-strip.js"></script>
          <script src="/resources/js/image-zoom.js"></script>
          <script src="/resources/js/photo-gallery.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/d3@7/dist/d3.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/d3-cloud@1/build/d3.layout.cloud.js"></script>
          <script src="/resources/js/wordcloud-overlay.js"></script>

    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

filters:
  - date-modified
  - hashtag
  - header-slug
  - ../shared/lua/render_start_timer.lua
  - ../shared/lua/span_multi.lua
  - ../shared/lua/filter_internal_links.lua
  - ../shared/lua/filter_stats_panel.lua
  - ../shared/lua/render_end_timer.lua

resources:
  - resources/icons/GB.svg
  - resources/icons/TR.svg
  - resources/audio/salim-1-16K-tr.vtt
  - "**/*_words.json" # All *_words.json files
  - "resources/json/word_labels.json" # Word cloud labels
  - "resources/images/markers/*.png" # Site map marker icons
  - "resources/images/map-card.png" # Map page social share card
