project:
  type: website
  output-dir: _site
  pre-render:
    - ../shared/bash/clean.sh
    - ../shared/python/precompute_reading_stats.py
    - ../shared/python/render_timer.py start
  post-render:
    - ../shared/bash/sync-tr.sh
    - ../shared/python/render_timer.py end
  preview:
    port: 7777

profiles:
  - dev
  - prod

lang: tr
reading-time:
  seconds-per-syllable: 0.2

hashtag:
  auto-scan: true
  default-provider: "x"

metadata:
  external-refs-title: "Dış Bağlantılar"
  phones:
    "0533XXX9779": "Nevzat Bahtiyar'ın kullandığı telefon numarası"
    "0536XXX7120": "Yüksel Güran'ın kullandığı telefon numarası"
    "0539XXX7358": "Enes Güran'ın kullandığı telefon numarası"
    "0530XXX0653": "Salim Güran'ın kullandığı telefon numarası"
    "0531XXX1521": "Selim Atasoy'un kullandığı telefon numarası"

  plates:
    "23 XX 630": "Nevzat Bahtiyar'ın kullandığı kırmızı araç"
    "47 XX 388": "Salim Güran'ın kullandığı araç"
    "56 XX 763": "Osman Güran'ın kullandığı araç"

  abbr:
    AAÜT: "Avukatlık Asgari Ücret Tarifesi"
    ACM: "Ağır Ceza Mahkemesi"
    AGO: "Adli Görüşme Odası"
    ATK: "Adli Tıp Kurumu"
    BTK: "Bilgi Teknolojileri ve İletişim Kurumu"
    BFI: "Brilliant Forensic Investigation"
    CMK: "Ceza Muhakemesi Kanunu"
    DEPSAŞ:  "Dicle Elektrik Perakende Satış A.Ş."
    "fer’i": "yan, tali"
    "zımni": "açıkça söylenmemiş ama dolaylı olarak var sayılan, ima edilen"
    GPS: "Global Positioning System - Küresel Konumlama Sistemi"
    HTS: "Historical Traffic Search - Geçmiş Trafik Verisi Sorgusu"
    JASAT: "Jandarma Suç Araştırma Timi"
    mtDNA: "Mitokondriyal DNA"
    TCK: "Türk Ceza Kanunu"
    TÜBİTAK: "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu"
    SEGBİS: "Ses ve Görüntü Bilişim Sistemi"
    UKB: "Ulusal Kriminal Büro"

  participant:
    victim:
      - variant: true
      - text: Maktul
      - prefix:
        - Maktul
      - suffix:
      - names:
        - "Narin Güran"
    suspect:
      - variant: true
      - text: Sanık
      - prefix:
        - Sanık
      - names:
        - "Nevzat Bahtiyar"
        - "Yüksel Güran"
        - "Salim Güran"
        - "Enes Güran"
    complainant:
      - variant: true
      - text: Katılan
      - prefix:
        - Katılan
      - names:
        - "Arif Güran"
    witness:
      - variant: true
      - text: Tanık
      - names:
        - "Muhammed Emre Güran"
        - "Maşşallah Güran"
        - "Maşallah Güran"
        - "Gazal Bahtiyar"
        - "Muhammed Kaya"
        - "Baran Güran"
        - "Osman Güran"
    judge:
      - text: Hakim
      - names:
        - "Mahkeme Başkanı"
        - "Mahkeme Üye Hakimi"
    prosecutor:
      - text: Savcı
      - names:
        - "Duruşma Savcısı"
    kdb:
      - text: "Diyarbakır Barosu"
      - prefix:
        - "Av."
      - names:
        - "Nahit Eren"
        - "Aydın Özdemir"
        - "Erdem Kaya"
        - "Mehdi Özdemir"
        - "Asya Cemre Işık"
        - "Berat Kocakaya"
        - "Derya Yıldırım"
        - "Metin Arkaş"
    ashb:
      - text: "Aile ve Sosyal Hiz. Bakanlığı"
      - prefix:
        - "Av."
      - names:
        - "Şeyhmus Erdoğan"
        - "Abdullah Yılmaz"
        - "Elif Aslı Şahin Torun"
        - "Emine Akçalı"
    mudafi-enes:
      - text: "Sanık Enes Güran Müdafi"
      - prefix:
        - "Av."
      - names:
        - "Mahir Akbilek"
        - "Mustafa Demir"
        - "Muhammed Fatih Demir"
        - "M. Fatih Demir"
        - "Recep Kızılok"
    mudafi-yuksel:
      - text: "Sanık Yüksel Güran müdafi"
      - prefix:
        - "Av."
      - names:
        - "Yılmaz Demiroğlu"
        - "Tuncay Erkuş"
        - "Furkan Çakır"
        - "Doğuş Can Kurucu"
        - "Sanık Yüksel Müdafi"
    mudafi-salim:
      - text: "Sanık Salim Güran müdafi"
      - prefix:
        - "Av."
      - names:
        - "Onur Akdağ"
    mudafi-nevzat:
      - text: "Sanık Nevzat Bahtiyar müdafi"
      - prefix:
        - "Av."
      - names:
        - "Ali Eryılmaz"
        - "Adnan Ataş"
    others:
      - text: "Diğer Katılımcılar"
      - names:
        - "Tercüman"
        - "Avukat Hanım"

highlight-style: a11y

website:
  title: "Narin"
  site-url: https://narinveailesiicinadalet.github.io/
  repo-url: https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io
  repo-branch: main
  image: resources/images/narin_tr.png
  favicon: resources/icons/favicon.png
  open-graph: true
  twitter-card: true
  repo-actions: [edit, issue]
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    left:
      - text: "{{< meta modification-date >}}"
      - text: "{{< meta render-time-footer >}}"
    center:
      - text: "<a class='nav-link footer-icon' href='/about' aria-label='About'><span class='svg-mask'></span>Hakkında</a>"
      - text:  "<a class='nav-link bi bi-patch-question' href='/faq' aria-label='SSS'><span class='svg-mask'></span> SSS</a>"
    right:
      - icon: twitter-x
        href: https://X.com/narinveailesi
        aria-label: Twitter
      - icon: github
        href: https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io
        aria-label: GitHub
      - icon: rss
        href: https://quarto.org/blog/index.xml
        aria-label: Blog RSS
  navbar:
    background: light
    logo: resources/icons/narin.png
    logo-href: /
    title: false
    collapse-below: lg
    left:
      - text: "Mahkeme"
        menu:
          - text: "Özet"
            icon: "file-medical"
            href: trial/index.qmd
          - text: "İfadeler"
            icon: "chat-left-text"
            href: trial/testimonies/index.qmd
          - text: "Savunma"
            icon: "files"
            href: trial/defenses/index.qmd
          - text: "Gerekçeli Karar"
            icon: "list-check"
            href: trial/judgment.qmd
      - text: "Yazılar"
        href: blog/index.qmd
      - text: "Harita"
        href: map/index.qmd
      - text: "Galeri"
        menu:
          - text: "Görseller"
            icon: "images"
            href: gallery/images/index.qmd
          - text: "Videolar"
            icon: "camera-video"
            href: gallery/videos/index.qmd
      - text: "Yardım"
        menu:
          - text: "Kılavuz"
            icon: "signpost-split"
            href: guide/index.qmd
          - text: "Eksik Bildir"
            icon: "bug"
            href: "https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io/issues"
          - text: "Soru sor"
            icon: "chat-right-text"
            href: "https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io/discussions"
          - text: "SSS"
            icon: "question-circle"
            href: faq/index.qmd
    tools:
      - icon: twitter-x
        href: https://X.com/narinveailesi
        text: Twitter
      - icon: github
        href: https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io
        text: GitHub
      - icon: chat-quote
        href: https://github.com/narinveailesiicinadalet/narinveailesiicinadalet.github.io/discussions
        text: Tartışma

  sidebar:
    - id: testimonies
      title: "İfadeler"
      style: "docked"
      collapse-level: 4
      align: left
      contents:
      - section: İfadeler
        href: trial/testimonies/index.qmd
        contents:
          - section: Sanıklar
            icon: "chat-left-text"
            href: trial/testimonies/suspect/index.qmd
            contents:
              - section: "Nevzat BAHTİYAR"
                icon: person-fill
                href: trial/testimonies/suspect/bahtiyar_nevzat/index.qmd
                contents:
                - text: "Mahkeme"
                  icon: dot
                  href: trial/testimonies/suspect/bahtiyar_nevzat/testimony.qmd
              - section: "Yüksel GÜRAN"
                icon: person-fill
                href: trial/testimonies/suspect/guran_yuksel/index.qmd
                contents:
                - text: "Mahkeme"
                  icon: dot
                  href: trial/testimonies/suspect/guran_yuksel/testimony.qmd
              - section: "Enes GÜRAN"
                icon: person-fill
                href: trial/testimonies/suspect/guran_enes/index.qmd
                contents:
                - text: "Mahkeme"
                  icon: dot
                  href: trial/testimonies/suspect/guran_enes/testimony.qmd
              - section: "Salim GÜRAN"
                icon: person-fill
                href: trial/testimonies/suspect/guran_salim/index.qmd
                contents:
                - text: "Mahkeme"
                  icon: dot
                  href: trial/testimonies/suspect/guran_salim/testimony.qmd
          - section: Tanıklar
            icon: "chat-left-text"
            href: trial/testimonies/witness/index.qmd
            contents:
              - text: "Gazal BAHTİYAR"
                icon: person
                href: trial/testimonies/witness/bahtiyar_gazal.qmd
              - text: "Baran GÜRAN"
                icon: person
                href: trial/testimonies/witness/guran_baran.qmd
              - text: "Maşşallah GÜRAN"
                icon: person
                href: trial/testimonies/witness/guran_masallah.qmd
              - text: "Osman GÜRAN"
                icon: person
                href: trial/testimonies/witness/guran_osman.qmd
              - text: "Muhammed KAYA"
                icon: person
                href: trial/testimonies/witness/kaya_muhammed.qmd

    - id: defenses
      title: "Savunmalar"
      style: "docked"
      collapse-level: 3
      align: left
      contents:
        - section: Savunmalar
          icon: "files"
          href: trial/defenses/index.qmd
          contents:
            - section: "Nevzat BAHTİYAR"
              icon: file-earmark-person
              href: trial/defenses/bahtiyar_nevzat/index.qmd
              contents:
              - text: "Av. Ali ERYILMAZ"
                icon: dot
                href: trial/defenses/bahtiyar_nevzat/eryilmaz_ali.qmd
              - text: "Av. Adnan ATAŞ"
                icon: dot
                href: trial/defenses/bahtiyar_nevzat/atas_adnan.qmd
            - section: "Yüksel GÜRAN"
              icon: file-earmark-person
              href: trial/defenses/guran_yuksel/index.qmd
              contents:
              - text: "Av. Yılmaz DEMİROĞLU"
                icon: dot
                href: trial/defenses/guran_yuksel/demiroglu_yilmaz.qmd
              - text: "Av. Furkan ÇAKIR"
                icon: dot
                href: trial/defenses/guran_yuksel/cakir_furkan.qmd
              - text: "Av. Doğuş Can KURUCU"
                icon: dot
                href: trial/defenses/guran_yuksel/kurucu_doguscan.qmd
            - section: "Enes GÜRAN"
              icon: file-earmark-person
              href: trial/defenses/guran_enes/index.qmd
              contents:
              - text: "Av. Mahir AKBİLEK"
                icon: dot
                href: trial/defenses/guran_enes/akbilek_mahir.qmd
              - text: "Av. M. Fatih DEMİR"
                icon: dot
                href: trial/defenses/guran_enes/demir_fatih.qmd
              - text: "Av. Recep KIZILOK"
                icon: dot
                href: trial/defenses/guran_enes/kizilok_recep.qmd
              - text: "Av. Mustafa DEMİR"
                icon: dot
                href: trial/defenses/guran_enes/demir_mustafa.qmd
            - section: "Salim GÜRAN"
              icon: file-earmark-person
              href: trial/defenses/guran_salim/index.qmd
              contents:
              - text: "Av. Onur AKDAĞ"
                icon: dot
                href: trial/defenses/guran_salim/akdag_onur.qmd

    - id: blog
      title: "Blog"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
      - section: Yazarlar
        contents:
          - text: Alaattin Oğuz
            icon: "file-earmark-person"
            href: blog/posts/alaattin-oguz/index.qmd
          - text: Ali Duran Topuz
            icon: "file-earmark-person"
            href: blog/posts/ali-duran-topuz/index.qmd
          - text: Cansu Çamlıbel
            icon: "file-earmark-person"
            href: blog/posts/cansu-camlibel/index.qmd
          - text: Cemal Tunçdemir
            icon: "file-earmark-person"
            href: blog/posts/cemal-tuncdemir/index.qmd
          - text: E. Miham Akkul
            icon: "file-earmark-person"
            href: blog/posts/miham-akkul/index.qmd
          - text: Faruk Bildirici
            icon: "file-earmark-person"
            href: blog/posts/faruk-bildirici/index.qmd
          - text: Hilal Seven
            icon: "file-earmark-person"
            href: blog/posts/hilal-seven/index.qmd
          - text: Melek Borak
            icon: "file-earmark-person"
            href: blog/posts/melek-borak/index.qmd
          - text: Nazife Güngör
            icon: "file-earmark-person"
            href: blog/posts/nazife-gungor/index.qmd
          - text: Ömer Faruk Gergerlioğlu
            icon: "file-earmark-person"
            href: blog/posts/omer-faruk-gergerlioglu/index.qmd
          - text: Rana Polat Sönmez
            icon: "file-earmark-person"
            href: blog/posts/rana-polat-sonmez/index.qmd
          - text: Sadık Güleç
            icon: "file-earmark-person"
            href: blog/posts/sadik-gulec/index.qmd
          - text: Sevilay Çelenk
            icon: "file-earmark-person"
            href: blog/posts/sevilay-celenk/index.qmd
          - text: Tuncay Beşikçi
            icon: "file-earmark-person"
            href: blog/posts/tuncay-besikci/index.qmd
          - text: Yıldıray Oğur
            icon: "file-earmark-person"
            href: blog/posts/yildiray-ogur/index.qmd
      - section: Haber Siteleri
        contents:
          - text: bianet
            icon: "newspaper"
            href: blog/posts/bianet/index.qmd
          - text: Serbestiyet
            icon: "newspaper"
            href: blog/posts/serbestiyet/index.qmd
          - text: T24
            icon: "newspaper"
            href: blog/posts/t24/index.qmd

    - id: images
      title: "Görseller"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
      - section: Görseller
        icon: "images"
        href: gallery/images/index.qmd
        contents:
          - text: Olay Yeri
            icon: "geo-alt"
            href: gallery/images/olay-yeri.qmd
          - text: Duruşmalar
            icon: "building"
            href: gallery/images/durusmalar.qmd
          - text: Adalet Nöbeti
            icon: "megaphone"
            href: gallery/images/adalet-nobeti.qmd
          - text: Arif Güran Ailesi
            icon: "people"
            href: gallery/images/aile.qmd
          - text: Basın-Röportaj
            icon: "mic"
            href: gallery/images/basin-roportaj.qmd
          - text: Narin
            icon: "person-heart"
            href: gallery/images/narin.qmd

    - id: videos
      title: "Videolar"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
      - section: Videolar
        icon: "camera-video"
        href: gallery/videos/index.qmd
        contents:
          - text: Belgeseller
            icon: "film"
            href: gallery/videos/belgeseller/index.qmd
          - text: Geçmiş Yayınlar
            icon: "broadcast"
            href: gallery/videos/gecmis-yayinlar/index.qmd
          - text: Rojda Altıntaş
            icon: "camera-reels"
            href: gallery/videos/rojda-altintas/index.qmd
          - text: Uğur Korkmaz
            icon: "camera-reels"
            href: gallery/videos/ugur-korkmaz/index.qmd

format:
  html:
    link-external-newwindow: true   # external linklere target="_blank"
    link-external-icon: true
    respect-user-color-scheme: true
    anchor-sections: false
    toc: true
    theme:
      light: [cosmo, resources/scss/theme.scss]
      dark: [cosmo, resources/scss/theme-dark.scss]
    css:
      - resources/css/styles.css
      - resources/css/span.css
      - resources/css/boxes.css
      - resources/css/mobile-toc.css
      - resources/css/highlight-speakers.css
      - resources/css/image-zoom.css
      - resources/css/refs.css
      - resources/css/stats_panel.css
      - resources/css/overlay.css
      - resources/css/margin-listing.css
      - resources/css/photo-gallery.css

    include-after-body:
      - text: |
          <script src="/resources/js/overlay.js"></script>
          <script src="/resources/js/hide-footer-actions.js"></script>
          <script src="/resources/js/external-links.js"></script>
          <script src="/resources/js/lang-switch-inject.js"></script>
          <script src="/resources/js/lang-switch-handler.js"></script>
          <script src="/resources/js/plate-tooltip.js"></script>
          <script src="/resources/js/toc-smooth-scroll.js"></script>
          <script src="/resources/js/mobile-toc-strip.js"></script>
          <script src="/resources/js/image-zoom.js"></script>
          <script src="/resources/js/photo-gallery.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/d3@7/dist/d3.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/d3-cloud@1/build/d3.layout.cloud.js"></script>
          <script src="/resources/js/wordcloud-overlay.js"></script>

    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

filters:
  - date-modified
  - hashtag
  - header-slug
  - ../shared/lua/render_start_timer.lua
  - ../shared/lua/span_multi.lua
  - ../shared/lua/filter_internal_links.lua
  - ../shared/lua/filter_stats_panel.lua
  - ../shared/lua/render_end_timer.lua

resources:
  - resources/icons/GB.svg
  - resources/icons/TR.svg
  - resources/audio/salim-1-16K-tr.vtt
  - "**/*_words.json" # All *_words.json files
  - "resources/json/word_labels.json" # Word cloud labels
  - "resources/images/markers/*.png" # Site map marker icons
  - "resources/images/map-card.png" # Map page social share card

